### ISSUE TITLE
find solution for conditional then steps

### ISSUE THREAD

**Issue by eiri020** [eiri020/bdh#12]
Following existing code is hard to implement in features, because events cannot support the not state, else we would have split up this into two scenarios:
```
  - id: kitchen_precense_state_changed
    alias: kitchen_precense_state_changed
    trigger:
      - platform: event
        event_type: precense_state_changed
    action:
      - choose:
          - conditions: "{{ trigger.event.data.state in ['present','relaxing'] }}"
            sequence:
              - service: script.kitchen_probe_light_off

        default:
          - service: script.kitchen_lights_off
          - service: media_player.turn_off
            target:
              entity_id: "{{ area_entities('Kitchen') | select('match', '^media_player\\.') | list }}"

```

**Comment by eiri020** [comment]
For now the solution might be as follows:
```
  Scenario Outline: House enters into a present state
    When the house enters into a <present state>
    Then adjust the kitchen lights

    Scenarios:
      | present state |
      | present       |
      | relaxing      |

  Scenario: House enters into a non-present state
    Given the triggered state WILL not be a present state
    When the house precense state changes
    Then turn off the kitchen lights
    And turn off all kitchen media
```

So misusing the Given not as an initial state but as a condition DURING the event.

My implementation looked like:
```
- alias: |-
    Scenario keuken: House enters into a non-present state
  id: scenario_keuken_house_enters_into_a_non_present_state
  mode: restart
  # GIVEN
  condition:
    - alias: |-
        Given the triggered state will not be a present state
      condition: template
      value_template: "{{ trigger.event.data.state not in ['present','relaxing'] }}"

  # WHEN
  trigger:
    # When the house precense state changes
    - platform: event
      event_type: precense_state_changed
```
It is valid to evaluate the trigger variables in the condition
